// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/unit/BarChart.vue')['default']
    BlockName: typeof import('./src/components/unit/BlockName.vue')['default']
    DateRangeSwitch: typeof import('./src/components/unit/DateRangeSwitch.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FeatureName: typeof import('./src/components/unit/FeatureName.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/feature/Home.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Menu: typeof import('./src/components/unit/Menu.vue')['default']
    MenuItem: typeof import('./src/components/unit/MenuItem.vue')['default']
    PerformanceCard: typeof import('./src/components/unit/PerformanceCard.vue')['default']
    PerformanceCardList: typeof import('./src/components/unit/PerformanceCardList.vue')['default']
    SideMenu: typeof import('./src/components/layout/SideMenu.vue')['default']
    Stats: typeof import('./src/components/feature/Stats.vue')['default']
  }
}

export {}
